package ru.webcrafter.core.entities;
// Generated 24.05.2012 21:24:36 by Hibernate Tools 3.2.2.GA


/**
 * ItemTemplate generated by hbm2java
 */
public class ItemTemplate implements java.io.Serializable {


    private String id;
    private int cost;

    public ItemTemplate() {
    }


    public ItemTemplate(String id) {
        this.id = id;
    }

    public ItemTemplate(String id, int cost) {
        this.id = id;
        this.cost = cost;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public int getCost() {
        return this.cost;
    }

    public void setCost(int cost) {
        this.cost = cost;
    }


}


