package ru.webcrafter.core.entities;
// Generated 24.05.2012 21:24:36 by Hibernate Tools 3.2.2.GA


import java.util.HashMap;
import java.util.Map;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {


    private long id;
    private long amount;
    private Map<String, Long> items = new HashMap<String, Long>(0);

    public User() {
    }


    public User(long id) {
        this.id = id;
    }

    public User(long id, long amount, Map<String, Long> items) {
        this.id = id;
        this.amount = amount;
        this.items = items;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getAmount() {
        return this.amount;
    }

    public void setAmount(long amount) {
        this.amount = amount;
    }

    public Map<String, Long> getItems() {
        return this.items;
    }

    public void setItems(Map<String, Long> items) {
        this.items = items;
    }


}


